public class Constants
{
    public const string LEAGUENAME = "Standard";
    public const int DEFAULT_PRICE = 0;

    public static readonly HashSet<string> townNames = new HashSet<string>()
    {
        "Lioneye's Watch",
        "The Forest Encampment",
        "The Sarn Encampment",
        "Highgate",
        "Overseer's Tower",
        "The Bridge Encampment",
        "Oriath Docks",
        "Oriath",
        "PvP Arena",
        "The Templar Laboratory",
        "Crumbled Laboratory",
        "Memory Nexus",
        "Karui Shores",
        "The Rogue Harbour",
        "Tane's Laboratory",
        "The Menagerie",
        "Mine Encampment",
        "Aspirants' Plaza",
        "Azurite Mine"
    }.Select(x => x.ToLower()).ToHashSet();

    public static readonly HashSet<string> actAreas = new HashSet<string>()
    {
          "The Twilight Strand",
          "The Coast",
          "The Tidal Island",
          "The Mud Flats",
          "The Fetid Pool",
          "The Submerged Passage",
          "The Flooded Depths",
          "The Ledge",
          "The Climb",
          "The Lower Prison",
          "The Upper Prison",
          "Prisoner's Gate",
          "The Ship Graveyard",
          "The Ship Graveyard Cave",
          "The Cavern of Wrath",
          "The Cavern of Anger",
          "The Southern Forest",
          "The Old Fields",
          "The Den",
          "The Riverways",
          "The Crossroads",
          "The Chamber of Sins Level 1",
          "The Chamber of Sins Level 2",
          "The Broken Bridge",
          "The Fellshrine Ruins",
          "The Crypt Level 1",
          "The Crypt Level 2",
          "The Western Forest",
          "The Weaver's Chambers",
          "The Wetlands",
          "The Vaal Ruins",
          "The Northern Forest",
          "The Dread Thicket",
          "The Caverns",
          "The Ancient Pyramid",
          "The City of Sarn",
          "The Slums",
          "The Crematorium",
          "The Sewers",
          "The Marketplace",
          "The Catacombs",
          "The Battlefront",
          "The Solaris Temple Level 1",
          "The Solaris Temple Level 2",
          "The Docks",
          "The Ebony Barracks",
          "The Lunaris Temple Level 1",
          "The Lunaris Temple Level 2",
          "The Imperial Garden",
          "The Library",
          "The Archives",
          "The Hedge Maze",
          "The Sceptre of God",
          "The Upper Sceptre of God",
          "The Aqueduct",
          "The Dried Lake",
          "The Mines Level 1",
          "The Mines Level 2",
          "The Crystal Veins",
          "Daresso's Dream",
          "The Grand Arena",
          "Kaom's Dream",
          "Kaom's Stronghold",
          "The Belly of the Beast Level 1",
          "The Belly of the Beast Level 2",
          "The Harvest",
          "The Ascent",
          "The Slave Pens",
          "The Control Blocks",
          "Oriath Square",
          "The Templar Courts",
          "The Chamber of Innocence",
          "The Torched Courts",
          "The Ruined Square",
          "The Ossuary",
          "The Reliquary",
          "The Cathedral Rooftop",
          "The Twilight Strand",
          "The Coast",
          "The Tidal Island",
          "The Mud Flats",
          "The Karui Fortress",
          "The Ridge",
          "The Lower Prison",
          "Shavronne's Tower",
          "Prisoner's Gate",
          "The Western Forest",
          "The Riverways",
          "The Wetlands",
          "The Southern Forest",
          "The Cavern of Anger",
          "The Beacon",
          "The Brine King's Reef",
          "The Broken Bridge",
          "The Crossroads",
          "The Fellshrine Ruins",
          "The Crypt",
          "The Chamber of Sins Level 1",
          "The Chamber of Sins Level 2",
          "Maligaro's Sanctum",
          "The Den",
          "The Ashen Fields",
          "The Northern Forest",
          "The Dread Thicket",
          "The Causeway",
          "The Vaal City",
          "The Temple of Decay Level 1",
          "The Temple of Decay Level 2",
          "The Sarn Ramparts",
          "The Toxic Conduits",
          "Doedre's Cesspool",
          "The Grand Promenade",
          "The Quay",
          "The Grain Gate",
          "The Imperial Fields",
          "The Solaris Temple Level 1",
          "The Solaris Temple Level 2",
          "The Solaris Concourse",
          "The Bath House",
          "The High Gardens",
          "The Lunaris Concourse",
          "The Lunaris Temple Level 1",
          "The Lunaris Temple Level 2",
          "The Harbour Bridge",
          "The Blood Aqueduct",
          "The Descent",
          "The Vastiri Desert",
          "The Oasis",
          "The Foothills",
          "The Boiling Lake",
          "The Tunnel",
          "The Quarry",
          "The Refinery",
          "The Belly of the Beast",
          "The Rotting Core",
          "The Cathedral Rooftop",
          "The Ravaged Square",
          "The Torched Courts",
          "The Desecrated Chambers",
          "The Ossuary",
          "The Reliquary",
          "The Canals",
          "The Feeding Trough",
          "The Fallen Courts",
          "The Haunted Reliquary",
          "The Imperial Gardens"
    }.Select(x => x.ToLower()).ToHashSet();
}




