using Newtonsoft.Json;
using Terminal.Gui;

//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace XileConsole
{
    public partial class ConfigView
    {

        public ConfigView()
        {
            InitializeComponent();

            if(File.Exists("Resources/userData.txt"))
            {
                string file = File.ReadAllText("Resources/userData.txt");
                UserData userData = JsonConvert.DeserializeObject<UserData>(file);

                poeSessIdTextField.Text = userData.poeSessId;
                accountNameTextField.Text = userData.poeAccountName;
                characterNameTextField.Text = userData.poeCharacterName;
                clientTxtField.Text = userData.clientTxt;
                foregroundColorPicker.SelectedColor = userData.foregroundColor;
                backgroundColorPicker.SelectedColor = userData.backgroundColor;
            }
            

            backButton.Clicked += () =>
            {
                Application.Run(new MainMenuView());
            };

            deleteMapsButton.Clicked += () =>
            {
                int answer = MessageBox.Query("Delete all maps", "Are you sure you want to delete all recorded maps?", "Yes", "No");
                if (answer == 0)
                {
                    if (File.Exists("Resources/mapData.txt"))
                    {
                        File.Delete("Resources/mapData.txt");
                    }
                }
            };

            deleteAllDataButton.Clicked += () =>
            {
                int answer = MessageBox.Query("Delete all poeNinja price data", "Are you sure you want to delete all poeNinja price data?\nThis will cause a force fetch the next time the data is used.", "Yes", "No");
                if (answer == 0)
                {
                    List<string> excludedFiles = new List<string>()
                    {
                        "inv.txt",
                        "mapData.txt",
                        "userData.txt"
                    };

                    if (Directory.Exists("Resources"))
                    {
                        DirectoryInfo di = new DirectoryInfo("Resources");
                        foreach(var file in di.GetFiles())
                        {
                            if(!excludedFiles.Contains(file.Name))
                            {
                                File.Delete($"Resources/{file.Name}");
                            }
                        }
                    }
                }
            };

            

            saveButton.Clicked += () =>
            {
                string leaguename = "";
                if(leagueRadioGroup.SelectedItem == 0)
                {
                    leaguename = Constants.LEAGUENAME;
                }
                else
                {
                    leaguename = "Standard";
                }
                
                saveLabel.Text = "Successfully saved!";
                UserData userData = new UserData(poeSessIdTextField.Text.ToString(),accountNameTextField.Text.ToString(), characterNameTextField.Text.ToString(), leaguename,clientTxtField.Text.ToString(),backgroundColorPicker.SelectedColor,foregroundColorPicker.SelectedColor);
                
                string res = JsonConvert.SerializeObject(userData);
                File.WriteAllText("Resources/userData.txt", res);
            };
        }
    }
}