using System;
using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace XileConsole
{
    public partial class ConfigView : Terminal.Gui.Window
    {
        private Terminal.Gui.FrameView configBorder;

        private Terminal.Gui.Label label;

        private Terminal.Gui.TextField poeSessIdTextField;

        private Terminal.Gui.Label label3;

        private Terminal.Gui.RadioGroup leagueRadioGroup;

        private Terminal.Gui.Label label2;

        private Terminal.Gui.TextField accountNameTextField;

        private Terminal.Gui.Label label4;

        private Terminal.Gui.TextField characterNameTextField;

        private Terminal.Gui.Label label5;

        private Terminal.Gui.TextField clientTxtField;

        private Terminal.Gui.Label label7;

        private Terminal.Gui.FrameView frameView;

        private Terminal.Gui.Button deleteAllDataButton;

        private Terminal.Gui.Button deleteMapsButton;

        private Terminal.Gui.FrameView frameView2;

        private Terminal.Gui.ColorPicker foregroundColorPicker;

        private Terminal.Gui.ColorPicker backgroundColorPicker;

        private Terminal.Gui.Button saveButton;

        private Terminal.Gui.Label saveLabel;

        private Terminal.Gui.Button backButton;

        private void InitializeComponent()
        {
            this.backButton = new Terminal.Gui.Button();
            this.saveLabel = new Terminal.Gui.Label();
            this.saveButton = new Terminal.Gui.Button();
            this.backgroundColorPicker = new Terminal.Gui.ColorPicker();
            this.foregroundColorPicker = new Terminal.Gui.ColorPicker();
            this.frameView2 = new Terminal.Gui.FrameView();
            this.deleteMapsButton = new Terminal.Gui.Button();
            this.deleteAllDataButton = new Terminal.Gui.Button();
            this.frameView = new Terminal.Gui.FrameView();
            this.label7 = new Terminal.Gui.Label();
            this.clientTxtField = new Terminal.Gui.TextField();
            this.label5 = new Terminal.Gui.Label();
            this.characterNameTextField = new Terminal.Gui.TextField();
            this.label4 = new Terminal.Gui.Label();
            this.accountNameTextField = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.leagueRadioGroup = new Terminal.Gui.RadioGroup();
            this.label3 = new Terminal.Gui.Label();
            this.poeSessIdTextField = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.configBorder = new Terminal.Gui.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.configBorder.Width = 116;
            this.configBorder.Height = 27;
            this.configBorder.X = 1;
            this.configBorder.Y = 0;
            this.configBorder.Data = "configBorder";
            this.configBorder.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.configBorder.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.configBorder.Border.Effect3D = false;
            this.configBorder.Border.Effect3DBrush = null;
            this.configBorder.Border.DrawMarginFrame = true;
            this.configBorder.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Title = "Config";
            this.Add(this.configBorder);
            this.label.Width = 6;
            this.label.Height = 1;
            this.label.X = 4;
            this.label.Y = 2;
            this.label.Data = "label";
            this.label.Text = "POESESSID:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.label);
            this.poeSessIdTextField.Width = 87;
            this.poeSessIdTextField.Height = 2;
            this.poeSessIdTextField.X = 20;
            this.poeSessIdTextField.Y = 2;
            this.poeSessIdTextField.Secret = false;
            this.poeSessIdTextField.Data = "poeSessIdTextField";
            this.poeSessIdTextField.Text = "";
            this.poeSessIdTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.poeSessIdTextField);
            this.label3.Width = 6;
            this.label3.Height = 1;
            this.label3.X = 4;
            this.label3.Y = 4;
            this.label3.Data = "label3";
            this.label3.Text = "League:";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.label3);
            this.leagueRadioGroup.Width = 10;
            this.leagueRadioGroup.Height = 2;
            this.leagueRadioGroup.X = 20;
            this.leagueRadioGroup.Y = 4;
            this.leagueRadioGroup.Data = "leagueRadioGroup";
            this.leagueRadioGroup.Text = "";
            this.leagueRadioGroup.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.leagueRadioGroup.RadioLabels = new NStack.ustring[] {
                    Constants.LEAGUENAME};
            this.leagueRadioGroup.DisplayMode = Terminal.Gui.DisplayModeLayout.Vertical;
            this.configBorder.Add(this.leagueRadioGroup);
            this.label2.Width = 6;
            this.label2.Height = 1;
            this.label2.X = 4;
            this.label2.Y = 6;
            this.label2.Data = "label2";
            this.label2.Text = "Account Name:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.label2);
            this.accountNameTextField.Width = 39;
            this.accountNameTextField.Height = 1;
            this.accountNameTextField.X = 20;
            this.accountNameTextField.Y = 6;
            this.accountNameTextField.Secret = false;
            this.accountNameTextField.Data = "accountNameTextField";
            this.accountNameTextField.Text = "";
            this.accountNameTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.accountNameTextField);
            this.label4.Width = 6;
            this.label4.Height = 1;
            this.label4.X = 4;
            this.label4.Y = 8;
            this.label4.Data = "label4";
            this.label4.Text = "Character Name:";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.label4);
            this.characterNameTextField.Width = 39;
            this.characterNameTextField.Height = 1;
            this.characterNameTextField.X = 20;
            this.characterNameTextField.Y = 8;
            this.characterNameTextField.Secret = false;
            this.characterNameTextField.Data = "characterNameTextField";
            this.characterNameTextField.Text = "";
            this.characterNameTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.characterNameTextField);
            this.label5.Width = 6;
            this.label5.Height = 1;
            this.label5.X = 4;
            this.label5.Y = 10;
            this.label5.Data = "label5";
            this.label5.Text = "client.txt";
            this.label5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.label5);
            this.clientTxtField.Width = 87;
            this.clientTxtField.Height = 2;
            this.clientTxtField.X = 20;
            this.clientTxtField.Y = 10;
            this.clientTxtField.Secret = false;
            this.clientTxtField.Data = "clientTxtField";
            this.clientTxtField.Text = "";
            this.clientTxtField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.clientTxtField);
            this.label7.Width = 5;
            this.label7.Height = 1;
            this.label7.X = 4;
            this.label7.Y = 12;
            this.label7.Data = "label7";
            this.label7.Text = "---------------------------------------------------------------------------------" +
                "----------------------";
            this.label7.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.label7);
            this.frameView.Width = 32;
            this.frameView.Height = 8;
            this.frameView.X = 4;
            this.frameView.Y = 15;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "Reset";
            this.configBorder.Add(this.frameView);
            this.deleteAllDataButton.Width = 24;
            this.deleteAllDataButton.Height = 1;
            this.deleteAllDataButton.X = 3;
            this.deleteAllDataButton.Y = 1;
            this.deleteAllDataButton.Data = "deleteAllDataButton";
            this.deleteAllDataButton.Text = "Force price re-fetch";
            this.deleteAllDataButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.deleteAllDataButton.IsDefault = false;
            this.frameView.Add(this.deleteAllDataButton);
            this.deleteMapsButton.Width = 28;
            this.deleteMapsButton.Height = 1;
            this.deleteMapsButton.X = 1;
            this.deleteMapsButton.Y = 3;
            this.deleteMapsButton.Data = "deleteMapsButton";
            this.deleteMapsButton.Text = "Delete all recorded maps";
            this.deleteMapsButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.deleteMapsButton.IsDefault = false;
            this.frameView.Add(this.deleteMapsButton);
            this.frameView2.Width = 69;
            this.frameView2.Height = 8;
            this.frameView2.X = 38;
            this.frameView2.Y = 15;
            this.frameView2.Data = "frameView2";
            this.frameView2.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView2.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameView2.Border.Effect3D = false;
            this.frameView2.Border.Effect3DBrush = null;
            this.frameView2.Border.DrawMarginFrame = true;
            this.frameView2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Title = "Application theme (requires restart to take effect)";
            this.configBorder.Add(this.frameView2);
            this.foregroundColorPicker.Width = 32;
            this.foregroundColorPicker.Height = 5;
            this.foregroundColorPicker.X = 1;
            this.foregroundColorPicker.Y = 1;
            this.foregroundColorPicker.Data = "foregroundColorPicker";
            this.foregroundColorPicker.Text = "Foreground color";
            this.foregroundColorPicker.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.foregroundColorPicker.SelectedColor = Color.Cyan;
            this.frameView2.Add(this.foregroundColorPicker);
            this.backgroundColorPicker.Width = 32;
            this.backgroundColorPicker.Height = 5;
            this.backgroundColorPicker.X = 34;
            this.backgroundColorPicker.Y = 1;
            this.backgroundColorPicker.Data = "backgroundColorPicker";
            this.backgroundColorPicker.Text = "Background color";
            this.backgroundColorPicker.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.backgroundColorPicker.SelectedColor = Color.Black;
            this.frameView2.Add(this.backgroundColorPicker);
            this.saveButton.Width = 18;
            this.saveButton.Height = 1;
            this.saveButton.X = 2;
            this.saveButton.Y = 24;
            this.saveButton.Data = "saveButton";
            this.saveButton.Text = "Confirm / Save";
            this.saveButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.saveButton.IsDefault = false;
            this.configBorder.Add(this.saveButton);
            this.saveLabel.Width = 4;
            this.saveLabel.Height = 1;
            this.saveLabel.X = 22;
            this.saveLabel.Y = 24;
            this.saveLabel.Data = "saveLabel";
            this.saveLabel.Text = "";
            this.saveLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.configBorder.Add(this.saveLabel);
            this.backButton.Width = 8;
            this.backButton.Height = 1;
            this.backButton.X = 1;
            this.backButton.Y = 27;
            this.backButton.Data = "backButton";
            this.backButton.Text = "Back";
            this.backButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.backButton.IsDefault = false;
            this.Add(this.backButton);
        }
    }
}
