using Terminal.Gui;

//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace XileConsole
{
    public partial class InventoryView
    {

        public InventoryView()
        {
            InitializeComponent();

            DataHandler.Instance.FetchInventory();

            backButton.Clicked += () =>
            {
                Application.Run(new MainMenuView());
            };

            totalValueInChaos.Text = "Total Value (chaos): " + DataHandler.Instance.inventoryHandler.GetInventoryValueInChaos().Truncate(2);
            totalValueInDivine.Text = "Total Value (divine): " + DataHandler.Instance.inventoryHandler.GetInventoryValueInDivine().Truncate(2);

            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();

            System.Data.DataColumn itemColumn;
            itemColumn = new System.Data.DataColumn();
            itemColumn.ColumnName = "Item";
            tableViewTable.Columns.Add(itemColumn);

            System.Data.DataColumn typeColumn;
            typeColumn = new System.Data.DataColumn();
            typeColumn.ColumnName = "Type";
            tableViewTable.Columns.Add(typeColumn);

            System.Data.DataColumn AmountColumn;
            AmountColumn = new System.Data.DataColumn();
            AmountColumn.ColumnName = "Amount";
            tableViewTable.Columns.Add(AmountColumn);

            System.Data.DataColumn PriceColumn;
            PriceColumn = new System.Data.DataColumn();
            PriceColumn.ColumnName = "Price";
            tableViewTable.Columns.Add(PriceColumn);

            System.Data.DataColumn TotalPriceColumn;
            TotalPriceColumn = new System.Data.DataColumn();
            TotalPriceColumn.ColumnName = "Total";
            tableViewTable.Columns.Add(TotalPriceColumn);

            foreach(var item in DataHandler.Instance.inventoryHandler.GetInventory())
            {
                tableViewTable.Rows.Add(item.name,item.ItemType.ToString(),item.stackSize,item.price.chaos.Truncate(2), (item.price.chaos * item.stackSize).Truncate(2));
            }



            this.tableView.Table = tableViewTable;
            this.inventoryBorder.Add(this.tableView);

            Application.Refresh();
        }
    }
}