using System;
using Terminal.Gui;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace XileConsole
{
    public partial class MainMenuView : Terminal.Gui.Window
    {
        private Terminal.Gui.FrameView frameView;
        private Terminal.Gui.ListView listView;
        private Terminal.Gui.Label label;

        private void InitializeComponent()
        {
            this.label = new Terminal.Gui.Label();
            this.listView = new Terminal.Gui.ListView();
            this.frameView = new Terminal.Gui.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.frameView.Width = 26;
            this.frameView.Height = 28;
            this.frameView.X = 1;
            this.frameView.Y = 0;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "Menu";
            this.Add(this.frameView);
            this.listView.Width = 20;
            this.listView.Height = 5;
            this.listView.X = 2;
            this.listView.Y = 1;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Inventory",
                        "Maps",
                        "Stash",
                        "Config",
                        "Exit"
                        });
            this.frameView.Add(this.listView);
            this.label.Width = 3;
            this.label.Height = 1;
            this.label.X = 35;
            this.label.Y = 10;
            this.label.Data = "label";
            this.label.Text = "__/\\\\\\_______/\\\\\\___/\\\\\\\\\\\\\\\\\\\\\\___/\\\\\\_______________/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_        \r\n _\\///\\\\\\___/\\\\\\/___\\/////\\\\\\///___\\/\\\\\\______________\\/\\\\\\///////////__       \r\n  ___\\///\\\\\\\\\\\\/_________\\/\\\\\\______\\/\\\\\\______________\\/\\\\\\_____________      \r\n   _____\\//\\\\\\\\___________\\/\\\\\\______\\/\\\\\\______________\\/\\\\\\\\\\\\\\\\\\\\\\_____     \r\n    ______\\/\\\\\\\\___________\\/\\\\\\______\\/\\\\\\______________\\/\\\\\\///////______    \r\n     ______/\\\\\\\\\\\\__________\\/\\\\\\______\\/\\\\\\______________\\/\\\\\\_____________   \r\n      ____/\\\\\\////\\\\\\________\\/\\\\\\______\\/\\\\\\______________\\/\\\\\\_____________  \r\n       __/\\\\\\/___\\///\\\\\\___/\\\\\\\\\\\\\\\\\\\\\\__\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\__\\/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_ \r\n        _\\///_______\\///___\\///////////___\\///////////////___\\///////////////__";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
        }
    }
}
