using Terminal.Gui;
using XileConsole.Misc;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace XileConsole
{
    public partial class MainMenuView
    {

        public MainMenuView()
        {
            InitializeComponent();

            if (!File.Exists("Resources/userData.txt"))
            {
                int i = MessageBox.Query("Info", "It seems like you have not configured XileConsole yet.\nPlease head to the config settings and provide the necessary data.", "Ok");

                if (i == 0)
                {
                    Application.Run(new ConfigView());
                }

            }

            listView.OpenSelectedItem += (e) =>
            {
                if(e.Item == 0)
                {
                    Application.Run(new InventoryView());
                }
                if (e.Item == 1)
                {
                    MapView view = new MapView();

                    Application.Run(view);
                }

                if (e.Item == 2)
                {
                    MessageBox.Query("Info", "This feature is not yet implemented.", "Ok");
                }

                if (e.Item == 3)
                {
                    Application.Run(new ConfigView());
                }
                if (e.Item == 4)
                {
                    Application.Shutdown();
                    Environment.Exit(0);
                }
            };
        }
    }
}
